year: 2026
contact_email: bsidesgoldie@gmail.com
event_date: May 23, 2026
cfp_close_date: TBD
cfp_url: https://bsidesgoldie.com/cfp.html
show_cfp: true
#logo_path: img/bsides-goldy-final.png
logo_path: img/gc_bsides_circular_logo.png
plugins:
  - jekyll-seo-tag
